service: starwars-queues-email

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  region: us-east-1
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
  environment: ${file(../../libs/configs.js)}

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!./**'

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-localstack
  - serverless-lift

custom:
  esbuild:
    bundle: true
    minify: true
  localstack: ${file(../../localstack.yml)}

constructs:
  email-queue:
    type: queue
    worker:
      handler: sendEmail/handler.method
      timeout: 10