service: starwars-backend-people

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  region: us-east-1
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AWSLambda_FullAccess
    - arn:aws:iam::aws:policy/SecretsManagerReadWrite
  environment: ${file(configs.js)}

package:
  individually: true
  exclude:
    - 'node_modules/**'
    - ./**

plugins:
  - serverless-openapi-documentation

custom:
  documentation: ${file(serverless.doc.yml):documentation}

functions:
  listPeople:
    handler: get-all-people/handler.method
    timeout: 8
    events:
      - http:
          method: get
          path: people/listPeople
    package:
      include:
        - './get-all-people/**'
        - './database.js'
        - './secret.js'
    layers:
      - ${cf:layers5-dev.Dependencias5LayerExport}
  
  createPerson:
    handler: create-new-person/handler.method
    timeout: 8
    events:
      - http:
          method: post
          path: people/createPerson
          documentation: ${file(serverless.doc.yml):documentation.endpoints.createPerson}
    package:
      include:
        - './create-new-person/**'
        - './database.js'
        - './secret.js'
    layers:
      - ${cf:layers5-dev.Dependencias5LayerExport}

  listPeopleSWAPI:
    handler: get-people-swapi/handler.method
    timeout: 8
    events:
      - http:
          method: get
          path: people/listPeopleSWAPI
    package:
      include:
        - './get-people-swapi/**'
    layers:
      - ${cf:layers5-dev.Dependencias5LayerExport}
